# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Andy Kamath
tagline:          'Just a kid on summer break'
description:      "80 Days of Summer Break. Just a blog of what I do every day to make myself productive"
url:              http://hyde.getpoole.com
baseurl:          /blog

author:
  name:           'Andy Kamath'
  url:            https://twitter.com/baesedandy

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/andykamath/blog
